apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agri-app
  labels:
    release: k8s-prometheus
spec:
  selector:
    matchLabels:
      app: agri-app
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
