apiVersion: v2
name: promtail
description: Promtail Helm chart
type: application
version: 0.1.0
appVersion: "2.9.0"

dependencies:
  - name: promtail
    version: 6.15.5
    repository: https://grafana.github.io/helm-charts