apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agri-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/islombay/agri-devops-assignment.git"
    targetRevision: main
    path: "helm/agri-app"
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: agri-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
