apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/islombay/agri-devops-assignment.git'
    targetRevision: HEAD
    path: k8s/grafana
    helm:
      valueFiles:
        - values.yaml

  # Target namespace in cluster
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring

  # Automatic sync
  syncPolicy:
    automated:
      prune: true          # Remove resources that are no longer in Git
      selfHeal: true       # Fix drift automatically
    syncOptions:
      - CreateNamespace=true # Create namespace if it doesn't exist
